dist: trusty
sudo: false

language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - "1.10"
  - tip

os:
  - linux
  - osx

before_install:
  - uname -a

script:
  - go test -v -cover ./...
  - go test -v -cover -race ./... -coverprofile=coverage.txt -covermode=atomic
  - go test -v -cover -race -benchmem -benchtime=5s -bench=.

matrix:
  allow_failures:
    - os: osx
    - go: tip

after_success:
  - bash <(curl -s https://codecov.io/bash)
