dist: focal

language: go

go:
  - "1.10"
  - "1.11"
  - "1.12"
  - "1.13"
  - "1.14"
  - "1.15"
  - "1.16"
  - tip

os:
  - linux
  - osx

before_install:
  - uname -a

script: ./test.bash

jobs:
  allow_failures:
    - os: osx
    - go: tip
